### ISSUE TITLE
Links are not shown correctly

### ISSUE THREAD

**Issue by hansmuff2** [EclipseFdn/eclipse.org-research#38]
Links in .md files in the format [Example] (https://example.com) work correctly when I run locally but not on eclipse.org/research. 
For example: https://www.eclipse.org/org/research/project/arrowhead_tools/

**Screenshots**
Locally: 
<img width="219" alt="image" src="https://user-images.githubusercontent.com/18737315/93774411-88f37b80-fc21-11ea-897d-f33e8f171e83.png">

eclipse.org/research:
<img width="555" alt="image" src="https://user-images.githubusercontent.com/18737315/93774518-a1fc2c80-fc21-11ea-91e7-4ff491cbbc4a.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - Browser: Firefox 80.0.1

**Comment by autumnfound** [comment]
In order to properly render in Hugo (and strict markdown environments), there should be no space between `[link text]` and `(#some-link-url)`. I'm not sure how it's properly rendering in your environment, maybe there is a Hugo version mismatch, and they have made changes to allow that in the newer version.

**Comment by chrisguindon** [comment]
This was solved with #39
