### ISSUE TITLE
Improving the research project page by adding Eclipse project dependencies

### ISSUE THREAD

**Issue by phkrief** [EclipseFdn/eclipse.org-research#40]
Dear Web Team,

We would like to improve the default template for the research project pages to include not only the Eclipse projects that the research contributes to but also the Eclipse projects that the research project uses. This will allow us to promote our projects and demonstrate that the research is (intensely) using Eclipse technologies.

the APPSTACLE is a great example using 7 Eclipse projects and we have a couple of research project which asked to be able to list used Eclipse technologies.

I have attached a possible layout as a suggestion. Your suggestions are of course more than welcome.

This is NOT an urgent request

Thanks a lot for your help

Kind regards
![new-research-project-page](https://user-images.githubusercontent.com/6196602/94035594-90eb2100-fdc3-11ea-923f-781578d5ac04.png)

**Comment by flora8984461** [comment]
Hello @phkrief , 

APPSTACLE is a best case scenario for this new idea. It might have issues in implementations for some of the other projects with longer content on the right side. If we make it full width, then there's a real chance we could have a significant gap between the content and the referenced projects. 
The following screenshot is just an example of what the potential issue would look like. 
![image](https://user-images.githubusercontent.com/39588094/95129840-9a607b80-0729-11eb-93f8-538ddb664bb4.png)

We probably need to think of a better design of how we want to implement this. @autumnfound  🤔

**Comment by phkrief** [comment]
Hi @flora8984461 

I understand it is an example. Nevertheless, it will be very exceptional to have more than 2 eclipse project on the right, knowing in 90% we will have only one. 
Now we could organize the layout differently, for example, like that:
![image](https://user-images.githubusercontent.com/6196602/95134318-fa274880-0762-11eb-9544-403d37216dcc.png)

WDYT?

**Comment by autumnfound** [comment]
A real-world example of this would be PANORAMA, which I've included below using the new style (rough mock, so some things differ):
![image](https://user-images.githubusercontent.com/23018241/95203078-3fbe3280-07b0-11eb-9edb-2f94e4ae7b38.png)

For a second example, here is one with the normal case (I realize its not perfect as it's in individual panels rather than one large panel, but its a quick mock up):
![image](https://user-images.githubusercontent.com/23018241/95203408-b65b3000-07b0-11eb-8742-17df4883402d.png)

I think this second style is more robust and accessible than the first style!

**Comment by phkrief** [comment]
+1 Thx @autumnfound

**Comment by flora8984461** [comment]
@phkrief Just FYI: currently only APPSTACLE has the Eclipse project info since this is the only info I was provided. You can add Eclipse projects to other projects as you wish like in the `content/project/appstacle.md` : `referenced_eclipse_projects: ["iot.ditto", "iot.hawkbit", "iot.hono", "iot.leshan", "ecd.che", "ecd.theia"]`

Or you can provide the info to us and we will add all for you. Thanks!
