### ISSUE TITLE
Canonical tag

### ISSUE THREAD

**Issue by phkrief** [EclipseFdn/eclipse.org-research#9]
In a few cases, we copy-paste some texts coming from other web pages.
Susan is recommending using the meta tag canonical, for example:
<link href="https://itea3.org/project/impact-stream/opees-impact-story.html" rel="canonical">
Can I inject such a tag in the middle of a Hugo text?

Thx

**Comment by autumnfound** [comment]
Currently that isn't possible, but I would ask why you would refer to an external site using the canonical meta tag? The canonical tag is used to point at the source of a piece of content when there are potential duplicates on the same site, rather than across different sites.

If this is a legal requirement, would placing a **Source: _link to external source_** on the page cover the requirement to cite the source?

**Comment by chrisguindon** [comment]
I agree with @autumnfound 

I think it would be great to add support for canonical urls for pages in our base theme but I wouldn't use it for your described use case. 

I would add a link to the source as described by Martin.

**Comment by phkrief** [comment]
I got this recommendation by Susan following this page: https://moz.com/learn/seo/canonicalization

I followed your suggestion. Thx
